# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='text',
        ),
    ]
