# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='like',
            new_name='likes',
        ),
    ]
