# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170621_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='likes',
            new_name='like',
        ),
    ]
