# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_book_in_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_audo',
            field=models.BooleanField(default=False),
        ),
    ]
