# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0003_book_in_audo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='in_audo',
            new_name='in_audio',
        ),
    ]
