# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('category', models.CharField(max_length=45)),
            ],
        ),
    ]
